### PR TITLE
fix: do not use Z flag on QEMU

### LINKED ISSUE #538: Stop using the Z flag on QEMU
@feloy noticed that the Z flag causes issues on QEMU

```
Error starting the application "ChatBot": starting container fed8637c0442e1bb56be148ebba4f34fbcdccbf86861fa60c95ceb17f52a3e26: lsetxattr /Users/phmartin/podman-desktop/ai-studio/models/hf.TheBloke.llama-2-7b-chat.Q5_K_S/llama-2-7b-chat.Q5_K_S.gguf: operation not supported
```

It works fine if it gets removed

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

it adds a check so that the Z flag is not used when working with qemu machine

### Screenshot / video of UI

N/A

### What issues does this PR fix or reference?

it resolves #538 

### How to test this PR?

1. run a recipe on qemu

### CODE REVIEW

**Review by jeffmaury — COMMENTED** [review]
As the process to detect if a machine is QEMU is MacOS specific I think we should ensure first we are on MacOS ?

**Comment by jeffmaury** [comment]
> As the process to detect if a machine is QEMU is quite heavy and MacOS specific I think we should ensure first we are on MacOS ?

**Comment by lstocchi** [comment]
> As the process to detect if a machine is QEMU is quite heavy and MacOS specific I think we should ensure first we are on MacOS ?

yes, good point. Updating

**Review by jeffmaury — APPROVED** [review]
LGTM. Tested on MacOS and Linux

**Pull request merged**
