### PR TITLE
fix: button must have a spinner when progress true

### PR DESCRIPTION
**Pull request by axel7083**
# Description 

Fixe Button svelte component to have proper spinner when progress true

# Screenshots

https://github.com/projectatomic/ai-studio/assets/42176370/b3d4adca-bea6-4fa7-a192-70e370b0a4d4

# Related issues

Fixes https://github.com/projectatomic/ai-studio/issues/188

# Tests

- [x] Regression tests has been added

### CODE REVIEW

**Comment by axel7083** [comment]
cc @slemeur

**Comment by benoitf** [comment]
I think that when modifying code duplicated from the core of podman desktop you should first discuss in the upstream before applying what I call 'downstream/ai-studio' library because your manual change will be easily dropped/forgotten when for example ai-studio' would use the podman desktop button component

**Comment by benoitf** [comment]
here for example you could use an icon for the 'send request' button as well
When in progress, icon will be replaced by the spinner

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
