### PR TITLE
fix: remove categories from catalog interface

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

We need to clear out some old dependencies/requirements (we have some hardcoded _recent_ category etc. which are not used), moreover categories where at the same level than Models and Recipe, removing for now. 

> We can re-introduce then later when we would have completed https://github.com/projectatomic/ai-studio/issues/447

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/461

### How to test this PR?

- [x] existing tests ensure no regression

### CODE REVIEW

**Comment by jeffmaury** [comment]
I don't understand the rationale for this. This is a change from the mockup and I don't remember being addressed during UI Call.
@slemeur @ekidneyrh WDYT ?

**Comment by axel7083** [comment]
> I don't understand the rationale for this. This is a change from the mockup and I don't remember being addressed during UI Call. @slemeur @ekidneyrh WDYT ?

If you want to split the models and the recipes. What do we do with the categories ?

**Comment by jeffmaury** [comment]
> > I don't understand the rationale for this. This is a change from the mockup and I don't remember being addressed during UI Call. @slemeur @ekidneyrh WDYT ?
> 
> If you want to split the models and the recipes. What do we do with the categories ?

They are related to recipes (a way to group and display them)

**Comment by axel7083** [comment]
> > > I don't understand the rationale for this. This is a change from the mockup and I don't remember being addressed during UI Call. @slemeur @ekidneyrh WDYT ?
> > 
> > 
> > If you want to split the models and the recipes. What do we do with the categories ?
> 
> They are related to recipes (a way to group and display them)

Okey got it. I will close this PR and include the change in https://github.com/projectatomic/ai-studio/pull/464

**Pull request closed without merging**
