### PR TITLE
chore: add code generation ai app to catalog

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

it adds the code generation application to the catalog

### Screenshot / video of UI

image

### What issues does this PR fix or reference?

it is part of #262 

### How to test this PR?

1. in the catalog you should see the new code generation app, run it and ask to generate code

### CODE REVIEW

**Review by axel7083 — APPROVED** [review]
A bit crazy but working fine!

image

**Review by jeffmaury — COMMENTED** [review]
The application/env never reaches the started state although the containers are ready as well as the UI

**Comment by lstocchi** [comment]
Do you have the same issue with the other apps? Or just this? I'm gonna check

**Comment by jeffmaury** [comment]
> Do you have the same issue with the other apps? Or just this? I'm gonna check

No chatbot is ok

**Comment by lstocchi** [comment]
@feloy @jeffmaury repliacted. This is also a problem that there is in the new chatbot. Investigating

**Comment by lstocchi** [comment]
@feloy @jeffmaury updated version to use the one with the model service check + the application is set to running if the containers are running. Please give it a try and let me know

**Review by feloy — APPROVED** [review]
works great for me

**Pull request merged**
