### PR TITLE
feat: recipe page responsive design

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Make the recipe page responsive. The Recipe/Application details will be placed on top on the `README.md` when the window size will reach a size of `1024px`. _(Ref https://tailwindcss.com/docs/responsive-design)_.

> The models tabs is a bit weird looking when the size is very small, the table itself is responsible of that behaviour, so we probably want **later** to improve the table component.

### Screenshot / video of UI

https://github.com/projectatomic/ai-studio/assets/42176370/dc2ecb57-7809-434d-83be-08f3fbaf81e4

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/258

### How to test this PR?

- (1) Open any recipe
- (2) Make the window size vary

### CODE REVIEW

**Comment by axel7083** [comment]
We might want to have @mairin opinion on the subject

**Review by lstocchi — COMMENTED** [review]
Looks great.
I would reduce the size to start moving the items (maybe medium or small, @mairin can be more helpful) and when it's completely shrink there is a small horizontal scrollbar

responsive

**Comment by axel7083** [comment]
@lstocchi  thanks for the tests! It was complicated to find, but the small horizontal bar was appearing because the text in the links in markdown where overflowing.

**Review by lstocchi — COMMENTED** [review]
I don't see the scrollbar when switching to the models tab, even though i can actually scroll down
responsive_scrollbar

when i open/close the details, the open/close icon do not maintain the same position
open_details

**Comment by axel7083** [comment]
@lstocchi I fixed the position of the toggle button. However, for the scrollbar, the issue is a bit complexe, the table has some hardcoded pixel values for the headers, and they are overflowing on the right, the scrollbar is hidden because of that.

The ideal fix would be to define `optional` column, that could be hidden when the size of the screen get too small.

For now, I cannot improve further the design nor fix the scroll bar without changing a lot the table component.

**Review by feloy — APPROVED** [review]
works great, thanks

**Pull request merged**
