### PR TITLE
feat: update design when running application

### LINKED ISSUE #163: Rename the pull application button to make it more clear
The name of the button is misleading and we should rename it to make it more clear.
Sally is proposing "Checkout and Build Locally" ->  https://docs.google.com/document/d/1TVVYf4fXywzdDF81EI11wrQcN5hbkpFF_Uf66TIoaoA/edit

@mairin any idea?

### PR DESCRIPTION
**Pull request by lstocchi**
### What does this PR do?

This PR just update the UI of the running application panel so that i can work on the switch model enhancement.
It renames the button, it creates a panel which is visible through all tabs and can be open/closed, and show the model used when running the application. Now it still uses llama as before.

### Screenshot / video of UI

refactor_design_run_app

### What issues does this PR fix or reference?

it is part of #201 
it closes #163 

### How to test this PR?

1. go to a recipe page and run the application.
2. everything should work as before, it just have a different UI

### CODE REVIEW

**Comment by lstocchi** [comment]
@mairin need to write some tests but the final aspect should be this one. WDYT? Maybe when the app is running we should show a stop button?

**Comment by feloy** [comment]
> @mairin need to write some tests but the final aspect should be this one. WDYT? Maybe when the app is running we should show a stop button? I'll add the swap button in the next PR where i'm going to work on switching models

As discussed with @jeffmaury, once the app is started, we would like to redirect the user to the Environments page, where it will be possible to manage (stop/...) the app.

**Comment by feloy** [comment]
You can probably remove the rounded corners on the top/bottom right corners of the floating window

**Comment by mairin** [comment]
This is awesome, @lstocchi!! This might be better in another PR but here's my idea for what controls to display once the application is running:

image

This raises some questions for me about how to handle the swap button... but I don't want to make a big tangent in this PR, I'll reach out in chat.

**Comment by lstocchi** [comment]
> You can probably remove the rounded corners on the top/bottom right corners of the floating window

You mean the left corners? I followed the mockup https://design.penpot.app/#/view/52961d58-0a92-80c2-8003-2a6919ad37d6?page-id=e6a8dc76-7670-80e5-8003-ccc1d3d7666d&section=interactions&index=8

**Comment by feloy** [comment]
> > You can probably remove the rounded corners on the top/bottom right corners of the floating window
> 
> You mean the left corners? I followed the mockup https://design.penpot.app/#/view/52961d58-0a92-80c2-8003-2a6919ad37d6?page-id=e6a8dc76-7670-80e5-8003-ccc1d3d7666d&section=interactions&index=8

No, really the right corners. I can see on the mockup that they are not rounded. The first corner at the top-right of the `>`

corner

**Comment by lstocchi** [comment]
> No, really the right corners. I can see on the mockup that they are not rounded. The first corner at the top-right of the `>` (below is a mockup screenshot)

I didn't see it, changing 👍

**Comment by axel7083** [comment]
@lstocchi really like the design, just one comment

image

We might not want to include the `favorite` while we have no implementation (we might just hide it)

**Review by axel7083 — APPROVED** [review]

**Comment by lstocchi** [comment]
> We might not want to include the `favorite` while we have no implementation (we might just hide it)

I talked with Mo about it and that does not represent the favorite anymore but the default model.
So with the next PR (that should allow swapping models) when you switch model you won't see it.

**Pull request merged**
