### PR TITLE
feat: set system prompt at the beginning

### LINKED ISSUE #617: Prevent modification of the system prompt after having started the playground's discussion
Following the work on #591 we would like to improve the behavior to be more consistent with how system prompt are used.

- The system prompt should be defined ONLY before starting the conversation.
- Once the conversation started, the system prompt is not editable anymore. 
- The user will see a message saying "Modifying the system prompt will significantly impact your entire playground. Unfortunately, you have limited options to make changes once the conversation has begun. Create a new playground and adjust the system prompt prior to initiating the interaction."

### PR DESCRIPTION
**Pull request by feloy**
### Screenshot / video of UI

https://github.com/projectatomic/ai-studio/assets/9973512/95f8dd99-541c-40b0-8518-e9647321b42f

### What issues does this PR fix or reference?

Part of #525 
Fixes #617

### CODE REVIEW

**Comment by jeffmaury** [comment]
Can't make it to work response is never returned

**Comment by feloy** [comment]
> Can't make it to work response is never returned

Could you please show me what you are doing exactly?

**Comment by jeffmaury** [comment]
> > Can't make it to work response is never returned
> 
> Could you please show me what you are doing exactly?

playground

**Comment by feloy** [comment]
> > > Can't make it to work response is never returned
> > 
> > 
> > Could you please show me what you are doing exactly?
> 
> playground [ playground ](https://private-user-images.githubusercontent.com/695993/315940584-3236c560-6739-443e-b9de-deed9cbc63cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTY0NjEsIm5iZiI6MTcxMTA5NjE2MSwicGF0aCI6Ii82OTU5OTMvMzE1OTQwNTg0LTMyMzZjNTYwLTY3MzktNDQzZS1iOWRlLWRlZWQ5Y2JjNjNjYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODI5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGVmODliM2VkYzMyYmI4ODhhNTM1NTZhNjljMGViNmZkYzRlYTNmMDUxYTBiN2EzMjEzNTY1ZTg3ZWVjMGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L48UDZeNcy83y16m6dz4b8juiyVpUIpLhlGCZGcGv8c) [ ](https://private-user-images.githubusercontent.com/695993/315940584-3236c560-6739-443e-b9de-deed9cbc63cc.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwOTY0NjEsIm5iZiI6MTcxMTA5NjE2MSwicGF0aCI6Ii82OTU5OTMvMzE1OTQwNTg0LTMyMzZjNTYwLTY3MzktNDQzZS1iOWRlLWRlZWQ5Y2JjNjNjYy5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwODI5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGVmODliM2VkYzMyYmI4ODhhNTM1NTZhNjljMGViNmZkYzRlYTNmMDUxYTBiN2EzMjEzNTY1ZTg3ZWVjMGExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L48UDZeNcy83y16m6dz4b8juiyVpUIpLhlGCZGcGv8c)

It seems it is not the good version. The system prompt textarea should appear at the top of the page (see demo on this issue's description)

**Comment by jeffmaury** [comment]
> > > > Can't make it to work response is never returned
> > > 
> > > 
> > > Could you please show me what you are doing exactly?
> > 
> 
> It seems it is not the good version. The system prompt textarea should appear at the top of the page (see demo on this issue's description)

Will retry but seems it's because of the window size

**Review by vrothberg — COMMENTED** [review]
Works well on my end 👍 
Screenshot 2024-03-22 at 10 30 13

**Comment by jeffmaury** [comment]
I don't have the set button but I'm not sure the UI is very intuitive and following the mock up

**Comment by jeffmaury** [comment]
> I don't have the set button but I'm not sure the UI is very intuitive and following the mock up

Got it working now: I was building on the backend 😡

**Comment by feloy** [comment]
> > I don't have the set button but I'm not sure the UI is very intuitive and following the mock up
> 
> Got it working now: I was building on the backend 😡

Please tell me if it is intuitive enough, or I can change to the mockup proposed by Axel

**Comment by jeffmaury** [comment]
> > > I don't have the set button but I'm not sure the UI is very intuitive and following the mock up
> > 
> > 
> > Got it working now: I was building on the backend 😡
> 
> Please tell me if it is intuitive enough, or I can change to the mockup proposed by Axel

For me it's not intuitive user should only have to enter the system prompt and user prompt and click Send. But maybe I'm biased. Asking Stevan review

**Comment by axel7083** [comment]
> > > > I don't have the set button but I'm not sure the UI is very intuitive and following the mock up
> > > 
> > > 
> > > Got it working now: I was building on the backend 😡
> > 
> > 
> > Please tell me if it is intuitive enough, or I can change to the mockup proposed by Axel
> 
> For me it's not intuitive user should only have to enter the system prompt and user prompt and click Send. But maybe I'm biased. Asking Stevan review

IMO, it should feel like it is facultative, as it is, having the large text area open by default could confuse the user on what he wants to do.

**Comment by feloy** [comment]
> > > > > I don't have the set button but I'm not sure the UI is very intuitive and following the mock up
> > > > 
> > > > 
> > > > Got it working now: I was building on the backend 😡
> > > 
> > > 
> > > Please tell me if it is intuitive enough, or I can change to the mockup proposed by Axel
> > 
> > 
> > For me it's not intuitive user should only have to enter the system prompt and user prompt and click Send. But maybe I'm biased. Asking Stevan review
> 
> IMO, it should feel like it is facultative, as it is, having the large text area open by default could confuse the user on what he wants to do.
> 
> We may want to discuss that in the UX call ? @feloy what do you think?

Yes, good point, I've added it to today's meeting notes. thanks

**Comment by feloy** [comment]
replaced by #643

**Pull request closed without merging**
