### PR TITLE
feat: use streaming in playground requests

### LINKED ISSUE #23: feat: adding streaming response for playground
The current implementation is requesting the full response before sending it to the front, most of libraries support Server Side Events, to "stream" the response, we need to support that as it is a standard.

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #23

### What does this PR do?

Use streaming when sending requests to the playground

### Screenshot / video of UI

streaming

### What issues does this PR fix or reference?

#23

### How to test this PR?

Just play with the playground

### CODE REVIEW

**Comment by axel7083** [comment]
> When testing on Linux, the following error is raised when calling `const client = new OpenAI({ baseURL: http://localhost:${state.container.port}/v1 });`:
> 
> ```
> Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
> ```

I am having the same issue

**Comment by jeffmaury** [comment]
> When testing on Linux, the following error is raised when calling `const client = new OpenAI({ baseURL: http://localhost:${state.container.port}/v1 });`:
> 
> ```
> Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
> ```

Should be fixed now

**Comment by jeffmaury** [comment]
> > When testing on Linux, the following error is raised when calling `const client = new OpenAI({ baseURL: http://localhost:${state.container.port}/v1 });`:
> > ```
> > Error: The OPENAI_API_KEY environment variable is missing or empty; either provide it, or instantiate the OpenAI client with an apiKey option, like new OpenAI({ apiKey: 'My API Key' }).
> > ```
> 
> I am having the same issue

Should be fixed now

**Review by lstocchi — APPROVED** [review]
Tested, works fine !!

**Review by feloy — APPROVED** [review]
tested, works on mac

**Review by axel7083 — APPROVED** [review]
Working on Windows 11.

Takes around ~6 GB of ram
image

**Pull request merged**
