### PR TITLE
feat: adding breadcrumbs

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Adding Breadcrumbs in a similar manner than Podman-Desktop.

> Implementation details: Podman-Desktop use a dedicated store to store the last page, however the webview of AI-Studio can and will be destoryed, re-created many time. making it complicated to save the last page nor relevant with the current UI. In this PR, for each page, we can optionally define a `lastpage` variable, that will display the breadcrumb corresponding.

### Screenshot / video of UI

**Model Service Details**

image

**Create Model Service**

image

**Create Playground**

image

**Playground Details**

image

**Recipe details**

image

**model details**

image

### What issues does this PR fix or reference?

Fixes https://github.com/projectatomic/ai-studio/issues/696

### How to test this PR?

Navigate in the pages of AI-Studio

### CODE REVIEW

**Comment by feloy** [comment]
Also fixes #551 ?

**Comment by feloy** [comment]
> **Model Service Details**
> 
> image
> 

It would be nice to have the name of the model, instead of 'Service Details'


Also, the Playground list page displays a breadcrumb `Playgrounds > Playgrounds environments`, which is not consistent with other pages at the same level, where there is no breadcrumb.

**Comment by axel7083** [comment]
> > **Model Service Details**
> > image
> 
> It would be nice to have the name of the model, instead of 'Service Details'
> 
> Also, the Playground list page displays a breadcrumb `Playgrounds > Playgrounds environments`, which is not consistent with other pages at the same level, where there is no breadcrumb.

I agree, but this should be made in a follow up PR as it changes the name of the pages properties.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
