### PR TITLE
feat(playground): introducing system prompt banner

### PR DESCRIPTION
**Pull request by axel7083**
### What does this PR do?

Improving the playground by allowing the user to change the system prompt after the creation.

### Screenshot / video of UI

**Creating a playground without system prompt**

image

**editing system prompt**

image

**system prompt edit finish**

image

**empty input**

image

### What issues does this PR fix or reference?

> That also means that there should be a way to "edit" the system prompt directly from the playground page.

Related to https://github.com/projectatomic/ai-studio/issues/660 

### How to test this PR?

- [x] unit tests has been provided

**manually**

- (1) Create a playground
- (2) set or not a system prompt
- (3) start a conversation or change the system prompt

### CODE REVIEW

**Comment by slemeur** [comment]
Nice addition! 

One case that I don't see in the video, is how do we handle the situation when there are already messages written in the chat? Are we blocking the ability to change the system prompt for the time being?

**Comment by axel7083** [comment]
> Nice addition!
> 
> One case that I don't see in the video, is how do we handle the situation when there are already messages written in the chat? Are we blocking the ability to change the system prompt for the time being?

Yes, the edit button is disabled

**Comment by vrothberg** [comment]
Apologies, I may not find time today to review and test.

**Comment by jeffmaury** [comment]
Strange vertical alignment:

image

**Comment by axel7083** [comment]
> Strange vertical alignment:

@jeffmaury could you explain more ? What are you talking about ? The distance between the top and the banner ?

**Comment by jeffmaury** [comment]
> > Strange vertical alignment:
> 
> @jeffmaury could you explain more ? What are you talking about ? The distance between the top and the banner ?

Vertical alignment between the System prompt block and the settings one

**Comment by axel7083** [comment]
> > > Strange vertical alignment:
> > 
> > 
> > @jeffmaury could you explain more ? What are you talking about ? The distance between the top and the banner ?
> 
> Vertical alignment between the System prompt block and the settings one

@jeffmaury I fixed the alignement, the issue was from the side panel css.

**Review by jeffmaury — APPROVED** [review]
LGTM

**Pull request merged**
