### PR TITLE
README: point to `:nightly` image

### PR DESCRIPTION
**Pull request by vrothberg**
The latest one is outdated and the nightly one has been recommended to me.  Others seemed to be unaware of the nightly one as well, so I propose to mention it for now.

It can certainly be changed in the future but for now I want to avoid others falling into the trap of using an old image.

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM - the title also says `Installing a development version` so it makes sense

**Comment by benoitf** [comment]
I think this PR is a dup (subpart of https://github.com/projectatomic/ai-studio/pull/233)

**Comment by jeffmaury** [comment]
> I think this PR is a dup (subpart of #233)

Yeah I wanted to add Valentin as reviewer for my PR but can't add him.

**Comment by benoitf** [comment]
> > I think this PR is a dup (subpart of #233)
> 
> Yeah I wanted to add Valentin as reviewer for my PR but can't add him.

fixed

**Pull request closed without merging**
