### PR TITLE
feat: display model icon in icons list

### PR DESCRIPTION
**Pull request by feloy**
### What does this PR do?

Displays a model icon in the models list. 

The icon is green when the model is downloaded.

### Screenshot / video of UI

model-icon

### What issues does this PR fix or reference?

Part of #479

### CODE REVIEW

**Comment by slemeur** [comment]
I like being able to more easily see the status of the model.
This icon is placeholder? Could we take the icons from HF?

**Review by jeffmaury — APPROVED** [review]
LGTM. Is there a way to have a unit test (switch between model downloaded or not ?)

**Comment by slemeur** [comment]
LGTM

**Comment by axel7083** [comment]
shoudn't the icon be green when the model is in use ? like the volume in podman desktop ? I feel like it would be a bit confusing ?

**Comment by feloy** [comment]
> shoudn't the icon be green when the model is in use ? like the volume in podman desktop ? I feel like it would be a bit confusing ?

@jeffmaury @slemeur WDYT?

**Comment by jeffmaury** [comment]
> > shoudn't the icon be green when the model is in use ? like the volume in podman desktop ? I feel like it would be a bit confusing ?
> 
> @jeffmaury @slemeur WDYT?

Could be a 1.0 follow up PR

**Pull request merged**
