### PR TITLE
dashboard: use a .svelte instead of .md

### PR DESCRIPTION
**Pull request by vrothberg**
### What does this PR do?

Now we can have on-click buttons that seem to be impossible to achieve when using markdown.

I am new to this, and really just copy-pasted things around until it looked as I imagined it to look (and worked).

### Screenshot / video of UI

Screenshot 2024-03-25 at 15 37 46

### CODE REVIEW

**Comment by vrothberg** [comment]
Waiting for feedback before addressing the CI issues.

**Comment by vrothberg** [comment]
I guess I need a helping hand to get CI green.

**Comment by feloy** [comment]
> I guess I need a helping hand to get CI green.

The test is expecting to find this (the element with label `inner-content`):

```
<div class="min-w-full flex-1 px-5 pt-5" aria-label="inner-content">
```

but you removed it. You could place this label in a `div` replacing the one you removed

**Comment by vrothberg** [comment]
Thanks for the guidance, @feloy! Much appreciated.

**Comment by vrothberg** [comment]
I think this fixes #624

**Comment by vrothberg** [comment]
@jeffmaury WDYT?

**Comment by vrothberg** [comment]
> > @jeffmaury WDYT?
> 
> The use of MD was to easy the authoring part. I'm not sure the dashboard will stay static

I agree.  It's certainly a compromise between ease of writing the text and the limited feature set of markdown.  I felt that having the clickable links is more important but I am not married to it.

@slemeur WDYT?

**Review by jeffmaury — APPROVED** [review]
LGTM

**Comment by slemeur** [comment]
Nice!

**Pull request merged**
